import Link from "next/link";
import RecordActions from "@/components/RecordActions";
import type { SP } from "@/lib/lists";
import { notFound } from "next/navigation";
import { db, schema as s } from "@/db";
import { authorize } from "@/lib/scope";
import { and, count, desc, eq, sum, sql } from "drizzle-orm";
import { PageHeader, Card, CardHeader, Badge, BtnLink, RecordLink, LinkableMetric, EmptyState } from "@/components/ui";
import { fmtDate, fmtDateTime, fmtMoney } from "@/lib/dates";
import { qs } from "@/lib/metrics";

export const dynamic = "force-dynamic";

export default async function AccountDetail({ params, searchParams }: {
  params: Promise<{ id: string }>;
  searchParams: Promise<SP>;
}) {
  const sp = await searchParams;
  const { id: idStr } = await params;
  const id = Number(idStr);
  const account = await authorize(await db.query.accounts.findFirst({ where: eq(s.accounts.id, id) }));
  if (!account) notFound();

  const [contacts, opportunities, events, leads, appointments, activities, tasks, campaigns, partner, location, tagRows, activityCount, apptStats] =
    await Promise.all([
      db.query.contacts.findMany({ where: eq(s.contacts.accountId, id) }),
      db.query.opportunities.findMany({ where: eq(s.opportunities.accountId, id), orderBy: [desc(s.opportunities.createdAt)] }),
      db.query.events.findMany({ where: eq(s.events.accountId, id), orderBy: [desc(s.events.startsAt)] }),
      db.query.leads.findMany({ where: eq(s.leads.accountId, id), orderBy: [desc(s.leads.createdAt)] }),
      db.query.appointments.findMany({ where: eq(s.appointments.accountId, id), orderBy: [desc(s.appointments.scheduledAt)] }),
      db.query.activities.findMany({ where: eq(s.activities.accountId, id), orderBy: [desc(s.activities.occurredAt)], limit: 15 }),
      db.query.tasks.findMany({ where: and(eq(s.tasks.accountId, id), eq(s.tasks.status, "Open")), orderBy: [s.tasks.dueDate] }),
      db.query.campaigns.findMany({ where: eq(s.campaigns.accountId, id) }),
      db.query.partners.findFirst({ where: eq(s.partners.accountId, id) }),
      account.clinicLocationId ? db.query.locations.findFirst({ where: eq(s.locations.id, account.clinicLocationId) }) : null,
      db.select({ name: s.tags.name }).from(s.accountTags).innerJoin(s.tags, eq(s.accountTags.tagId, s.tags.id)).where(eq(s.accountTags.accountId, id)),
      db.select({ c: count() }).from(s.activities).where(eq(s.activities.accountId, id)),
      db.select({
        c: count(),
        charged: sum(s.appointments.revenue),
        collected: sum(sql`case when ${s.appointments.collected} then ${s.appointments.revenue} else 0 end`),
      }).from(s.appointments).where(eq(s.appointments.accountId, id)),
    ]);

  const info: [string, React.ReactNode][] = [
    ["Vertical", account.vertical],
    ["Area", account.area],
    ["Illumin8 location", location?.name ?? "—"],
    ["Phone", account.phone ?? "—"],
    ["Email", account.email ?? "—"],
    ["Website", account.website ? <a key="w" href={account.website} target="_blank" className="text-accent-deep hover:underline">{account.website.replace(/^https?:\/\//, "")}</a> : "—"],
    ["Address", account.address ?? "—"],
    ["Owner / contact", account.ownerName ?? "—"],
    ["Source", account.source ?? "—"],
    ["Partnership potential", "★".repeat(account.partnershipScore) + "☆".repeat(5 - account.partnershipScore)],
    ["Event potential", "★".repeat(account.eventScore) + "☆".repeat(5 - account.eventScore)],
    ["Added", fmtDate(account.createdAt)],
  ];

  return (
    <div className="mx-auto max-w-6xl">
      <PageHeader
        title={<span className="flex items-center gap-3">{account.name}
          {account.doNotContact && <span className="rounded-full bg-bad-soft px-2.5 py-0.5 text-xs font-semibold text-bad">Do Not Contact</span>}
        </span>}
        subtitle={<span className="flex items-center gap-2"><Badge>{account.status}</Badge><Badge>{account.relationshipStrength}</Badge>
          {tagRows.map((t) => <span key={t.name} className="rounded-full bg-hairline px-2.5 py-0.5 text-xs text-soft">{t.name}</span>)}
        </span>}
        actions={<>
          <BtnLink variant="outline" href={`/accounts/${id}/edit`}>Edit</BtnLink>
          <BtnLink variant="outline" href={`/tasks/new${qs({ accountId: id })}`}>New Task</BtnLink>
          <BtnLink href={`/activities/new${qs({ accountId: id })}`}>Log Activity</BtnLink>
        </>} />

      {/* Metrics generated by this business — all clickable */}
      <div className="grid grid-cols-2 gap-3 md:grid-cols-5">
        <LinkableMetric label="Activities" value={Number(activityCount[0]?.c ?? 0)} href={`/activities${qs({ accountId: id })}`} />
        <LinkableMetric label="Opportunities" value={opportunities.length} href={`/opportunities${qs({ accountId: id })}`} />
        <LinkableMetric label="Events" value={events.length} href={`/events${qs({ accountId: id })}`} />
        <LinkableMetric label="Leads" value={leads.length} href={`/leads${qs({ accountId: id })}`} />
        <LinkableMetric label="Appointments" value={Number(apptStats[0]?.c ?? 0)}
          sub={`${fmtMoney(Number(apptStats[0]?.collected ?? 0))} of ${fmtMoney(Number(apptStats[0]?.charged ?? 0))} collected`}
          href={`/appointments${qs({ accountId: id })}`} />
      </div>

      <div className="mt-5 grid gap-5 lg:grid-cols-3">
        <div className="space-y-5 lg:col-span-2">
          {/* Opportunities */}
          <Card>
            <CardHeader title="Opportunities" action={
              <Link href={`/opportunities/new${qs({ accountId: id })}`} className="text-xs font-medium text-accent-deep hover:underline">+ New</Link>} />
            {opportunities.length === 0 ? (
              <p className="px-5 pb-4 text-sm text-faint">No opportunities yet.</p>
            ) : (
              <table className="tbl">
                <thead><tr><th>Name</th><th>Stage</th><th>Type</th><th>Next follow-up</th></tr></thead>
                <tbody>{opportunities.map((o) => (
                  <tr key={o.id}>
                    <td><RecordLink href={`/opportunities/${o.id}`}>{o.name}</RecordLink></td>
                    <td><Badge>{o.stage}</Badge></td>
                    <td className="text-soft">{o.type}</td>
                    <td className="text-soft">{fmtDate(o.nextFollowUpAt)}</td>
                  </tr>))}
                </tbody>
              </table>
            )}
          </Card>

          {/* Events */}
          <Card>
            <CardHeader title="Events" action={
              <Link href={`/events/new${qs({ accountId: id })}`} className="text-xs font-medium text-accent-deep hover:underline">+ New</Link>} />
            {events.length === 0 ? (
              <p className="px-5 pb-4 text-sm text-faint">No events with this business yet.</p>
            ) : (
              <table className="tbl">
                <thead><tr><th>Event</th><th>Date</th><th>Status</th><th>Appts</th></tr></thead>
                <tbody>{events.map((e) => {
                  const apptCount = appointments.filter((a) => a.eventId === e.id).length;
                  return (
                    <tr key={e.id}>
                      <td><RecordLink href={`/events/${e.id}`}>{e.name}</RecordLink></td>
                      <td className="text-soft">{fmtDateTime(e.startsAt)}</td>
                      <td><Badge>{e.status}</Badge></td>
                      <td>{apptCount > 0
                        ? <RecordLink href={`/appointments${qs({ eventId: e.id })}`}>{apptCount}</RecordLink>
                        : <span className="text-faint">0</span>}</td>
                    </tr>
                  );
                })}
                </tbody>
              </table>
            )}
          </Card>

          {/* Activity timeline */}
          <Card>
            <CardHeader title="Activity Timeline" action={
              <Link href={`/activities${qs({ accountId: id })}`} className="text-xs font-medium text-accent-deep hover:underline">View all</Link>} />
            {activities.length === 0 ? (
              <EmptyState icon="bolt" title="No activity logged yet"
                action={<BtnLink variant="outline" href={`/activities/new${qs({ accountId: id })}`}>Log the first touch</BtnLink>} />
            ) : (
              <ul className="px-5 pb-5">
                {activities.map((a) => (
                  <li key={a.id} className="relative border-l border-line py-2.5 pl-5 last:pb-0">
                    <span className="absolute -left-[5px] top-[18px] h-2.5 w-2.5 rounded-full border-2 border-card bg-accent" />
                    <p className="text-sm"><span className="font-medium">{a.type}</span>
                      {a.outcome && <> · <Badge>{a.outcome}</Badge></>}
                      <span className="ml-2 text-xs text-faint">{fmtDateTime(a.occurredAt)}</span></p>
                    {a.notes && <p className="mt-0.5 text-sm text-soft">{a.notes}</p>}
                  </li>
                ))}
              </ul>
            )}
          </Card>
        </div>

        <div className="space-y-5">
          {/* Business info */}
          <Card>
            <CardHeader title="Business Info" />
            <dl className="space-y-2 px-5 pb-5 text-sm">
              {info.map(([k, v]) => (
                <div key={k} className="flex justify-between gap-3">
                  <dt className="shrink-0 text-faint">{k}</dt>
                  <dd className="text-right font-medium text-ink">{v}</dd>
                </div>
              ))}
            </dl>
            {account.notes && <p className="border-t border-hairline px-5 py-4 text-sm text-soft">{account.notes}</p>}
          </Card>

          {/* Contacts */}
          <Card>
            <CardHeader title="Contacts" action={
              <Link href={`/contacts/new${qs({ accountId: id })}`} className="text-xs font-medium text-accent-deep hover:underline">+ New</Link>} />
            {contacts.length === 0 ? (
              <p className="px-5 pb-4 text-sm text-faint">No contacts yet.</p>
            ) : (
              <ul className="px-2 pb-2">
                {contacts.map((c) => (
                  <li key={c.id}>
                    <Link href={`/contacts/${c.id}`} className="block rounded-xl px-3 py-2 transition-colors hover:bg-hairline">
                      <span className="block text-sm font-medium">{c.firstName} {c.lastName}</span>
                      <span className="block text-xs text-soft">{c.title ?? c.contactType}{c.phone ? ` · ${c.phone}` : ""}</span>
                    </Link>
                  </li>
                ))}
              </ul>
            )}
          </Card>

          {/* Partner + campaigns */}
          {(partner || campaigns.length > 0) && (
            <Card>
              <CardHeader title="Partnership & Campaigns" />
              <ul className="px-2 pb-2">
                {partner && (
                  <li><Link href={`/partners/${partner.id}`} className="block rounded-xl px-3 py-2 transition-colors hover:bg-hairline">
                    <span className="flex items-center justify-between text-sm font-medium">{partner.partnerType}<Badge>{partner.status}</Badge></span>
                    {partner.dropBoxActive && <span className="text-xs text-soft">Drop box: {partner.dropBoxStatus ?? "Active"}</span>}
                  </Link></li>
                )}
                {campaigns.map((c) => (
                  <li key={c.id}><Link href={`/campaigns/${c.id}`} className="block rounded-xl px-3 py-2 transition-colors hover:bg-hairline">
                    <span className="flex items-center justify-between text-sm font-medium">{c.name}<Badge>{c.status}</Badge></span>
                  </Link></li>
                ))}
              </ul>
            </Card>
          )}

          {/* Open tasks */}
          <Card>
            <CardHeader title="Open Tasks" action={
              <Link href={`/tasks/new${qs({ accountId: id })}`} className="text-xs font-medium text-accent-deep hover:underline">+ New</Link>} />
            {tasks.length === 0 ? (
              <p className="px-5 pb-4 text-sm text-faint">Nothing pending.</p>
            ) : (
              <ul className="px-2 pb-2">
                {tasks.map((t) => (
                  <li key={t.id}>
                    <Link href={`/tasks/${t.id}`} className="block rounded-xl px-3 py-2 transition-colors hover:bg-hairline">
                      <span className="block text-sm font-medium">{t.title}</span>
                      <span className="block text-xs text-soft">Due {fmtDate(t.dueDate)}</span>
                    </Link>
                  </li>
                ))}
              </ul>
            )}
          </Card>
        </div>
      </div>

      <RecordActions kind="account" id={id} name={account.name} sp={sp} />
    </div>
  );
}
